apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1-alpine
          name: nginx
          resources: {}
      initContainers:
        - name: init-myservice
          image: busybox
          command: ["sh", "-c", "set -eux; echo $(BRANCH_NAME); echo $(NON_EXISTENT_ENV)"]
          env:
            - name: BRANCH_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['branch-name']
            - name: NON_EXISTENT_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['non-existent-env']
